[versions]
kotlin = "1.9.22"
compose-plugin = "1.6.0"
agp = "8.3.1"
buildkonfig = "0.15.1"

androidx-activity-compose = "1.8.2"
compose = "1.6.4"

koin-version = "3.6.0-wasm-alpha2"
precompose-version = "1.6.0-rc05"
generativeai = "0.2.0-1.0.0-wasm"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-version" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-version" }

precompose = { module = "moe.tlaster:precompose", version.ref = "precompose-version" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose-version" }
precompose-koin = { module = "moe.tlaster:precompose-koin", version.ref = "precompose-version" }

generativeai = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "generativeai" }

[bundles]
koin = ["koin-core", "koin-compose"]
precompose = ["precompose", "precompose-viewmodel", "precompose-koin"]

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }