[versions]
# ---------- Shared ---------
kotlin = "1.9.23"
buildkonfig = "0.15.1"
generativeai = "0.2.0-1.0.0"

# ---------- Compose ----------
compose-plugin = "1.6.1"
koin-bom = "3.5.3"
precompose-version = "1.6.0-rc05"
ktor = "2.3.10"

# ---------- Android ----------
agp = "8.3.1"
androidx-activity-compose = "1.8.2"
compose = "1.6.5"

# ---------- Desktop ----------
slf4j = "2.0.12"

# ------------ Js ------------
kobweb = "0.17.1"

[libraries]
# ---------- Shared ---------
generativeai = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "generativeai" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.3" }

# ---------- Compose ----------
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose-version" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose-version" }
precompose-koin = { module = "moe.tlaster:precompose-koin", version.ref = "precompose-version" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-logging = { module = "io.ktor:ktor-client-logging" }

# ---------- Android ----------
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
koin-android = { module = "io.insert-koin:koin-android" }
ktor-android = { module = "io.ktor:ktor-client-android" }

# ---------- Desktop ----------
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# ------------ Js ------------
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core ", version.ref = "kobweb" }
kobweb-silk = { module = "com.varabyte.kobweb:kobweb-silk", version.ref = "kobweb" }
kobwebx-markdown = { module = "com.varabyte.kobwebx:kobwebx-markdown", version.ref = "kobweb" }
silk-icons-fa = { module = "com.varabyte.kobwebx:silk-icons-fa", version.ref = "kobweb" }
silk-icons-mdi = { module = "com.varabyte.kobwebx:silk-icons-mdi", version.ref = "kobweb" }

[bundles]
koin = ["koin-core", "koin-compose"]
precompose = ["precompose", "precompose-viewmodel", "precompose-koin"]
ktor = ["ktor-core", "ktor-content-negotiation", "ktor-serialization-json", "ktor-logging"]

[plugins]
# ---------- Shared ---------
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kobwebLibrary = { id = "com.varabyte.kobweb.library", version.ref = "kobweb" }

# ---------- Compose ----------
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

# ---------- Android ----------
androidApplication = { id = "com.android.application", version.ref = "agp" }

# ------------ Js ------------
kobwebApplication = { id = "com.varabyte.kobweb.application", version.ref = "kobweb" }
kobwebxMarkdown = { id = "com.varabyte.kobwebx.markdown", version.ref = "kobweb" }
